title: Sailesh's website
description: Download resume, proffesional pic, etc.
theme: just-the-docs

url: saileshb10.github.io/website/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
